import serial.tools.list_ports
import sqlite3
import datetime
import os
import serial
import requests
import time

UPLOAD_EVERY_SECONDS = 10
BATCH_SIZE = 1000
HTTP_TIMEOUT = (3, 10) #timeout for how long it takes to connect (connect timeout), timeout for how long it takes to read the information (read timeout)

SQLITE_DB = "testing.db"

#send to terminal before running the code
SUPABASE_URL = os.environ.get("SUPABASE_URL")  
SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_KEY")  

def get_supabase_headers() -> dict:
    """
    Returns the required authentication and content headers for Supabase REST
    API requests using the service role key.
    """
    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        raise RuntimeError("Missing SUPABASE_URL or SUPABASE_SERVICE_KEY environment variables.")
    return {
        "apikey": SUPABASE_SERVICE_KEY,
        "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=minimal",
    }

def upload_batch_to_supabase(rows: list[tuple]) -> bool:
    """
    Takes the batch of entries, stores them in a list of dictionaries and sends an HTTP request to send the entries to Supabase.
    If True is returned, the request was successful.
    If False is returned, the request was unsuccessful.
    """
    if not rows: #if there are no rows to upload, the upload was successful
        return True
    
    payload = []
    
    for r in rows: #all entries are stored in a dictionary, which is the format in which Supabase accepts information
        entry = {}
        entry["time"] = r[1]
        entry["sensor_type"] = r[2]
        entry["value"] = r[3]
        payload.append(entry) #all dictionary entries are stored in the payload list
        
    url = f"{SUPABASE_URL}/rest/v1/data" #constructs URL for the Supabase REST API
    #REST API is a standard way for software programs to communicate over the internet using HTTP requests
    
    try:
        response = requests.post(  #gets the response to how the request was handled (status codes 200-299 are successful)
            url,
            headers = get_supabase_headers(),
            json = payload, #converts python data into JSON because REST APIs require text-based formats
            timeout = HTTP_TIMEOUT
        )
        
        if 200 <= response.status_code < 300: #if the request was successful
            return True
        
        print(f"[UPLOAD FAIL] status={response.status_code} body={response.text[:200]}") #prints the response status code and the server's error message
        return False
    except requests.RequestException as e: #catches any HTTP/network failure
         print(f"[UPLOAD ERROR] {e}") #text is generated by requests library and converts exception to text
         return False
        
def mark_rows_upload(conn, ids) -> None:
    """
    Changes the uploaded status of entries that have been uploaded to Supabase to 1.
    """
    if not ids: #checks if list is empty
        return
    
    for row_id in ids:
        conn.execute(
        "UPDATE data SET uploaded = 1 WHERE id = (?)",
        (row_id,)
        )
    
    conn.commit()

    
def upload_backlog(conn) -> None: 
    """
    Uploads any SQLite database entries to Supabase that have not been uploaded yet, 
    including new entries and old entries that failed.
    """
    cur = conn.cursor()
    cur.execute(
        """
        SELECT id, time, sensor_type, value
        FROM data
        WHERE uploaded = 0
        ORDER BY time ASC
        LIMIT ?
        """,
        (BATCH_SIZE,)
    )
    
    rows = cur.fetchall() #stores all of the selected data as a list of tuples
    
    if not rows: #if there are no entries to be uploaded, exit the function
        return
    
    ok = upload_batch_to_supabase(rows) #returns whether the rows were successfully sent to Supabase
    
    
    if ok: #if successful, change uploaded = 1
        ids = []
        for r in rows:
            row_id = r[0]
            ids.append(row_id)
            
        mark_rows_upload(conn, ids)
        print(f"[UPLOAD OK] uploaded {len(ids)} rows")
    #keeps uploaded = 0 if not ok



def choose_com_port() -> str:
    """
    Select the port that the Arduino is connected to. This allows the program to receive the Arduino's data.
    """
    ports = serial.tools.list_ports.comports()
    portsList = []

    for onePort in ports:
        portsList.append(str(onePort))
        print(str(onePort))
        
    val = input("Select Port: COM")

    for x in range(0,len(portsList)):
        if portsList[x].startswith("COM" + str(val)):
            return "COM" + str(val)
    raise RuntimeError("Selected COM port not found.")


def main():
    #connect to database
    conn = sqlite3.connect(SQLITE_DB)

    #new rows are written into a side log to avoid database locking if reading occurs at the same time as writing
    conn.execute("PRAGMA journal_mode=WAL;")
    #syncs batches of data to disk
    conn.execute("PRAGMA synchronous=NORMAL;")

    #create a cursor
    c = conn.cursor()

    #Drop Table
    c.execute("DROP TABLE data")
    conn.commit()

    #create a table
    c.execute("""CREATE TABLE data (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        time TEXT,
        sensor_type TEXT,
        value REAL,
        uploaded INTEGER NOT NULL DEFAULT 0
        )""")


    serialInst = serial.Serial()
    portVar = choose_com_port()
    serialInst.baudrate = 9600
    serialInst.port = portVar
    serialInst.timeout = 1
    serialInst.open()

    sensor_types = ['INPUT_HPi', 
                    'INPUT_HPo', 
                    'INPUT_TANKi', 
                    'INPUT_TANKo', 
                    'INPUT_GNDi', 
                    'INPUT_GNDo', 
                    'INPUT_AIRo',
                    'MODE',
                    'MODE_heat_floor',
                    'MODE_heat_forced',
                    'MODE_cool_forced',
                    'MODE_proactive',
                    'INPUT_PUMP_PWR_HP',
                    'STATE_HP_O',
                    'STATE_HP_Y',
                    'STATE_PUMP_HP',
                    'STATE_PUMP_BMNT',
                    'STATE_PUMP_1ST2ND',
                    'STATE_AH_W',
                    'STATE_AH_O',
                    'STATE_AH_Y',
                    'STATE_AH_G',
                    'CriticalFlag',
                    'PowerAlarmLevelFlag',
                    'TempAlarmLevelFlag',
                    'RelayAlarmLevelFlag'
                    ]
    
    #first upload check starts immediately when loop starts
    last_upload_attempt = 0.0

    #empty list that will put the tuples into the table
    one_row_data = []

    try:
        while True:
            now = time.time()
            if now - last_upload_attempt >= UPLOAD_EVERY_SECONDS:
                last_upload_attempt = now
                upload_backlog(conn)
                
            if serialInst.in_waiting:
                packet = serialInst.readline()
                #strip data and turn it into a list
                packet_list = packet.decode("utf-8", errors = "ignore").strip().split()
                #turn data into floats
                try:
                    packet_floats = [float(x) for x in packet_list]
                except ValueError:
                    continue
                
                if len(packet_floats) != len(sensor_types):
                    continue
                
                time_stamp = datetime.datetime.now(datetime.timezone.utc).isoformat()
                for i in range(len(sensor_types)):
                    #put data into a tuple so that it can fit into the table
                    tuple_unit = (time_stamp, sensor_types[i], packet_floats[i])
                    one_row_data.append(tuple_unit)
                
                c.executemany("INSERT INTO data (time, sensor_type, value) VALUES (?,?,?)", one_row_data)
                conn.commit()
                                
                c.execute("SELECT id, time, sensor_type, value, uploaded FROM data ORDER BY id")
                data_table = c.fetchall()
                for data in data_table:
                    print(data)
                
                #print(packet_list)
                #print(one_row_data)
                one_row_data.clear()
                
            time.sleep(0.1)
    finally:
        try:
            serialInst.close()
        except Exception:
            pass
        conn.close()
            
if __name__ == "__main__":
    main()


